### ISSUE TITLE
Dude - something's wrong with your title

### ISSUE THREAD

**Issue by MonZta123** [mbanushi/EternalConwayFlames#1]
;l fkajs;dlfiu asleijf a;soiejf a;oiewj f;kajs d;foiaj se;oifja h;sojh foashd;f oa jise;foaijl eflha selufha lsefhalkjhdfalshe flqjiwhflkjash dfliauhw eflia

**Comment by mbanushi** [comment]
Wtf ive no idea where that came from. I do t even own a cat
